version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
      - image: postgres:latest
      - image: redis:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo
    steps:
      - run: npm i -g azure-cli
      - run: npm i -g azure-functions-core-tools
      - run: npm i -g azure-functions-pack
      - run: azure login -u ${AZURE_USERNAME} -p ${AZURE_PASSWORD}
      - run: func azure functionapp publish test-api-123

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master